-- =============================================
-- UNIVERSITY GRADE MANAGEMENT SYSTEM
-- Step 7: Oracle Label Security (OLS) Configuration
-- Scenario: Secure Exam Question Bank
-- =============================================
-- Prerequisites:
--   - Oracle Database 19c+ with OLS option
--   - OLS must be enabled (run as SYSDBA):
--     EXEC LBACSYS.CONFIGURE_OLS;
--     EXEC LBACSYS.OLS_ENFORCEMENT.ENABLE_OLS;
-- =============================================

SET ECHO ON
SET FEEDBACK ON
SET SERVEROUTPUT ON

ALTER SESSION SET CONTAINER = ORCLPDB;

-- =============================================
-- 0. CHECK OLS STATUS
-- =============================================
PROMPT
PROMPT =============================================
PROMPT Checking OLS Installation Status...
PROMPT =============================================

-- Check if OLS is installed
SELECT comp_id, comp_name, version, status
FROM dba_registry
WHERE comp_id = 'OLS';

-- If OLS is not installed, you need to run as SYSDBA:
-- EXEC LBACSYS.CONFIGURE_OLS;
-- EXEC LBACSYS.OLS_ENFORCEMENT.ENABLE_OLS;

-- =============================================
-- 1. GRANT OLS ADMINISTRATIVE PRIVILEGES
-- =============================================
PROMPT
PROMPT =============================================
PROMPT Granting OLS Administrative Privileges...
PROMPT =============================================

-- Grant LBAC_DBA role to GMS_ADMIN
GRANT LBAC_DBA TO GMS_ADMIN;

-- Grant execute privileges on OLS packages
GRANT EXECUTE ON sa_sysdba TO GMS_ADMIN;
GRANT EXECUTE ON sa_components TO GMS_ADMIN;
GRANT EXECUTE ON sa_label_admin TO GMS_ADMIN;
GRANT EXECUTE ON sa_policy_admin TO GMS_ADMIN;
GRANT EXECUTE ON sa_user_admin TO GMS_ADMIN;
GRANT EXECUTE ON sa_session TO GMS_ADMIN;

PROMPT OLS privileges granted to GMS_ADMIN.

-- =============================================
-- 2. SWITCH TO GMS_ADMIN SCHEMA
-- =============================================
ALTER SESSION SET CURRENT_SCHEMA = GMS_ADMIN;

-- =============================================
-- 3. CREATE EXAM_QUESTIONS TABLE
-- =============================================
PROMPT
PROMPT =============================================
PROMPT Creating EXAM_QUESTIONS table...
PROMPT =============================================

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE EXAM_QUESTIONS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN 
        IF SQLCODE != -942 THEN -- Table does not exist
            RAISE;
        END IF;
END;
/

CREATE TABLE EXAM_QUESTIONS (
    question_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_code VARCHAR2(10),
    question_text VARCHAR2(500),
    correct_answer VARCHAR2(200),
    created_by VARCHAR2(50),
    created_date DATE DEFAULT SYSDATE,
    -- Cột này sẽ chứa nhãn OLS (số)
    ols_label NUMBER
);

PROMPT EXAM_QUESTIONS table created successfully.

-- =============================================
-- 4. DROP EXISTING POLICY (IF EXISTS)
-- =============================================
PROMPT
PROMPT =============================================
PROMPT Dropping existing OLS policy (if any)...
PROMPT =============================================

BEGIN
    -- Xóa policy cũ nếu có (tránh lỗi khi chạy lại)
    SA_SYSDBA.DROP_POLICY(policy_name => 'EXAM_SEC_POLICY', drop_column => TRUE);
    PROMPT Existing policy dropped.
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -12420 THEN -- Policy does not exist
            PROMPT No existing policy found (this is OK).
        ELSE
            RAISE;
        END IF;
END;
/

-- =============================================
-- 5. CREATE OLS POLICY
-- =============================================
PROMPT
PROMPT =============================================
PROMPT Creating OLS Policy: EXAM_SEC_POLICY...
PROMPT =============================================

BEGIN
    SA_SYSDBA.CREATE_POLICY (
        policy_name      => 'EXAM_SEC_POLICY',
        column_name      => 'OLS_LABEL',
        default_options  => 'READ_CONTROL, WRITE_CONTROL, LABEL_DEFAULT'
    );
    PROMPT Policy EXAM_SEC_POLICY created successfully.
EXCEPTION
    WHEN OTHERS THEN
        PROMPT Error creating policy: || SQLERRM;
        RAISE;
END;
/

-- =============================================
-- 6. CREATE LEVELS (Cấp độ bảo mật)
-- =============================================
PROMPT
PROMPT =============================================
PROMPT Creating Security Levels...
PROMPT =============================================

BEGIN
    -- Levels (Cấp độ)
    -- Số càng lớn -> Bảo mật càng cao
    
    -- Level 1000: PUBLIC - Công khai
    SA_COMPONENTS.CREATE_LEVEL('EXAM_SEC_POLICY', 1000, 'PUB', 'PUBLIC');
    PROMPT Level PUB (1000) created.
    
    -- Level 2000: INTERNAL - Nội bộ
    SA_COMPONENTS.CREATE_LEVEL('EXAM_SEC_POLICY', 2000, 'INT', 'INTERNAL');
    PROMPT Level INT (2000) created.
    
    -- Level 3000: CONFIDENTIAL - Mật
    SA_COMPONENTS.CREATE_LEVEL('EXAM_SEC_POLICY', 3000, 'CONF', 'CONFIDENTIAL');
    PROMPT Level CONF (3000) created.
    
EXCEPTION
    WHEN OTHERS THEN
        PROMPT Error creating levels: || SQLERRM;
        RAISE;
END;
/

-- =============================================
-- 7. CREATE COMPARTMENTS (Khoa/Phòng ban)
-- =============================================
PROMPT
PROMPT =============================================
PROMPT Creating Compartments (Departments)...
PROMPT =============================================

BEGIN
    -- Compartments (Khoa/Phòng ban)
    SA_COMPONENTS.CREATE_COMPARTMENT('EXAM_SEC_POLICY', 100, 'CS', 'COMPUTER SCIENCE');
    PROMPT Compartment CS created.
    
    SA_COMPONENTS.CREATE_COMPARTMENT('EXAM_SEC_POLICY', 200, 'EE', 'ELECTRICAL ENGINEERING');
    PROMPT Compartment EE created.
    
EXCEPTION
    WHEN OTHERS THEN
        PROMPT Error creating compartments: || SQLERRM;
        RAISE;
END;
/

-- =============================================
-- 8. CREATE DATA LABELS (Nhãn dữ liệu)
-- =============================================
PROMPT
PROMPT =============================================
PROMPT Creating Data Labels...
PROMPT =============================================

BEGIN
    -- Label công khai (cho sinh viên)
    SA_LABEL_ADMIN.CREATE_LABEL('EXAM_SEC_POLICY', 1000, 'PUB', TRUE);
    PROMPT Label PUB created.
    
    -- Label nội bộ khoa CS
    SA_LABEL_ADMIN.CREATE_LABEL('EXAM_SEC_POLICY', 2100, 'INT:CS', TRUE);
    PROMPT Label INT:CS created.
    
    -- Label nội bộ khoa EE
    SA_LABEL_ADMIN.CREATE_LABEL('EXAM_SEC_POLICY', 2200, 'INT:EE', TRUE);
    PROMPT Label INT:EE created.
    
    -- Label MẬT khoa CS (Đáp án thi)
    SA_LABEL_ADMIN.CREATE_LABEL('EXAM_SEC_POLICY', 3100, 'CONF:CS', TRUE);
    PROMPT Label CONF:CS created.
    
EXCEPTION
    WHEN OTHERS THEN
        PROMPT Error creating labels: || SQLERRM;
        RAISE;
END;
/

-- =============================================
-- 9. APPLY POLICY TO TABLE
-- =============================================
PROMPT
PROMPT =============================================
PROMPT Applying Policy to EXAM_QUESTIONS table...
PROMPT =============================================

BEGIN
    SA_POLICY_ADMIN.APPLY_TABLE_POLICY (
        policy_name    => 'EXAM_SEC_POLICY',
        schema_name    => 'GMS_ADMIN',
        table_name     => 'EXAM_QUESTIONS',
        table_options  => 'READ_CONTROL, WRITE_CONTROL, LABEL_DEFAULT'
    );
    PROMPT Policy applied to EXAM_QUESTIONS table successfully.
EXCEPTION
    WHEN OTHERS THEN
        PROMPT Error applying policy: || SQLERRM;
        RAISE;
END;
/

-- =============================================
-- 10. AUTHORIZE USERS (Cấp quyền cho users)
-- =============================================
PROMPT
PROMPT =============================================
PROMPT Authorizing Users...
PROMPT =============================================

-- 10.1. GMS_STUDENT: Chỉ được đọc mức thấp nhất (PUB)
PROMPT
PROMPT Authorizing GMS_STUDENT (PUB read only)...
BEGIN
    SA_USER_ADMIN.SET_USER_LABELS (
        policy_name  => 'EXAM_SEC_POLICY',
        user_name    => 'GMS_STUDENT',
        max_read_label => 'PUB'
    );
    PROMPT GMS_STUDENT authorized: Can read PUB level only.
EXCEPTION
    WHEN OTHERS THEN
        PROMPT Error authorizing GMS_STUDENT: || SQLERRM;
        RAISE;
END;
/

-- 10.2. GMS_LECTURER: Được đọc/ghi mức INTERNAL của khoa CS
PROMPT
PROMPT Authorizing GMS_LECTURER (INT:CS read/write)...
BEGIN
    SA_USER_ADMIN.SET_USER_LABELS (
        policy_name  => 'EXAM_SEC_POLICY',
        user_name    => 'GMS_LECTURER',
        max_read_label => 'INT:CS',
        max_write_label => 'INT:CS',
        min_write_label => 'PUB',
        def_label       => 'INT:CS',
        row_label       => 'INT:CS'
    );
    PROMPT GMS_LECTURER authorized: Can read/write INT:CS level.
EXCEPTION
    WHEN OTHERS THEN
        PROMPT Error authorizing GMS_LECTURER: || SQLERRM;
        RAISE;
END;
/

-- 10.3. GMS_DEAN: Được đọc mức cao nhất (CONFIDENTIAL) của khoa CS
PROMPT
PROMPT Authorizing GMS_DEAN (CONF:CS read/write)...
BEGIN
    SA_USER_ADMIN.SET_USER_LABELS (
        policy_name  => 'EXAM_SEC_POLICY',
        user_name    => 'GMS_DEAN',
        max_read_label => 'CONF:CS', -- Đọc được cả CONF, INT, PUB của CS
        max_write_label => 'CONF:CS',
        min_write_label => 'PUB',
        def_label       => 'CONF:CS',
        row_label       => 'CONF:CS'
    );
    PROMPT GMS_DEAN authorized: Can read/write CONF:CS level.
EXCEPTION
    WHEN OTHERS THEN
        PROMPT Error authorizing GMS_DEAN: || SQLERRM;
        RAISE;
END;
/

-- 10.4. GMS_ADMIN: Quyền lực tối thượng (để debug)
PROMPT
PROMPT Authorizing GMS_ADMIN (FULL privileges)...
BEGIN
    SA_USER_ADMIN.SET_USER_PRIVS (
        policy_name => 'EXAM_SEC_POLICY',
        user_name   => 'GMS_ADMIN',
        privileges  => 'FULL' -- Bypass hết OLS
    );
    PROMPT GMS_ADMIN authorized: FULL privileges (bypass OLS).
EXCEPTION
    WHEN OTHERS THEN
        PROMPT Error authorizing GMS_ADMIN: || SQLERRM;
        RAISE;
END;
/

-- =============================================
-- 11. INSERT SAMPLE DATA
-- =============================================
PROMPT
PROMPT =============================================
PROMPT Inserting Sample Data...
PROMPT =============================================

-- Câu hỏi công khai (Ai cũng thấy)
INSERT INTO EXAM_QUESTIONS (subject_code, question_text, correct_answer, created_by, ols_label)
VALUES ('CS101', 'Sample Question 1: What is 1+1?', '2', 'SYSTEM', CHAR_TO_LABEL('EXAM_SEC_POLICY', 'PUB'));

-- Câu hỏi nội bộ khoa CS (Chỉ GV và Dean CS thấy)
INSERT INTO EXAM_QUESTIONS (subject_code, question_text, correct_answer, created_by, ols_label)
VALUES ('CS102', 'Internal Question: Explain QuickSort?', 'O(nlogn)', 'LEC001', CHAR_TO_LABEL('EXAM_SEC_POLICY', 'INT:CS'));

-- Câu hỏi nội bộ khoa EE (GV khoa CS KHÔNG thấy)
INSERT INTO EXAM_QUESTIONS (subject_code, question_text, correct_answer, created_by, ols_label)
VALUES ('EE201', 'Internal EE: Ohm Law?', 'V=IR', 'LEC004', CHAR_TO_LABEL('EXAM_SEC_POLICY', 'INT:EE'));

-- Câu hỏi MẬT khoa CS (Chỉ Dean CS thấy)
INSERT INTO EXAM_QUESTIONS (subject_code, question_text, correct_answer, created_by, ols_label)
VALUES ('CS101', 'FINAL EXAM ANSWER KEY 2025', 'Option A, C, D...', 'DEAN001', CHAR_TO_LABEL('EXAM_SEC_POLICY', 'CONF:CS'));

COMMIT;

PROMPT Sample data inserted successfully.

-- =============================================
-- 12. VERIFICATION QUERIES
-- =============================================
PROMPT
PROMPT =============================================
PROMPT Verification Queries
PROMPT =============================================

PROMPT
PROMPT 1. Checking OLS Policy:
SELECT policy_name, status
FROM dba_sa_policies
WHERE policy_name = 'EXAM_SEC_POLICY';

PROMPT
PROMPT 2. Checking Levels:
SELECT level_num, short_name, long_name
FROM dba_sa_levels
WHERE policy_name = 'EXAM_SEC_POLICY'
ORDER BY level_num;

PROMPT
PROMPT 3. Checking Compartments:
SELECT comp_num, short_name, long_name
FROM dba_sa_compartments
WHERE policy_name = 'EXAM_SEC_POLICY'
ORDER BY comp_num;

PROMPT
PROMPT 4. Checking Labels:
SELECT label_tag, label
FROM dba_sa_labels
WHERE policy_name = 'EXAM_SEC_POLICY'
ORDER BY label_tag;

PROMPT
PROMPT 5. Checking User Authorizations:
SELECT user_name, max_read_label, max_write_label, min_write_label
FROM dba_sa_user_levels
WHERE policy_name = 'EXAM_SEC_POLICY'
ORDER BY user_name;

PROMPT
PROMPT 6. Checking Sample Data (as GMS_ADMIN - should see all):
SELECT question_id, subject_code, 
       SUBSTR(question_text, 1, 30) as question_preview,
       LABEL_TO_CHAR(ols_label) as security_label
FROM gms_admin.EXAM_QUESTIONS
ORDER BY question_id;

PROMPT
PROMPT =============================================
PROMPT OLS Policy Configured Successfully!
PROMPT =============================================
PROMPT
PROMPT Summary:
PROMPT   - Policy: EXAM_SEC_POLICY
PROMPT   - Table: EXAM_QUESTIONS
PROMPT   - Levels: PUB (1000), INT (2000), CONF (3000)
PROMPT   - Compartments: CS, EE
PROMPT   - Labels: PUB, INT:CS, INT:EE, CONF:CS
PROMPT   - Users authorized: GMS_STUDENT, GMS_LECTURER, GMS_DEAN, GMS_ADMIN
PROMPT
PROMPT Test OLS:
PROMPT   1. Connect as GMS_STUDENT and query EXAM_QUESTIONS (should see only PUB)
PROMPT   2. Connect as GMS_LECTURER and query EXAM_QUESTIONS (should see PUB + INT:CS)
PROMPT   3. Connect as GMS_DEAN and query EXAM_QUESTIONS (should see all CS labels)
PROMPT
PROMPT =============================================

