-- =============================================
-- UNIVERSITY GRADE MANAGEMENT SYSTEM
-- User Creation Script (Simplified - Using existing tablespaces)
-- System B: Quy trình quản lý điểm trong trường đại học
-- =============================================

-- Drop existing users if they exist
BEGIN
    FOR usr IN (SELECT username FROM dba_users WHERE username LIKE 'GMS_%') LOOP
        BEGIN
            EXECUTE IMMEDIATE 'DROP USER ' || usr.username || ' CASCADE';
        EXCEPTION
            WHEN OTHERS THEN NULL;
        END;
    END LOOP;
END;
/

-- Create main application user (using default tablespaces)
CREATE USER GMS_ADMIN IDENTIFIED BY "Admin@2024#Secure"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

-- Grant privileges to admin user
GRANT CONNECT, RESOURCE, DBA TO GMS_ADMIN;
GRANT CREATE SESSION TO GMS_ADMIN;
GRANT CREATE TABLE TO GMS_ADMIN;
GRANT CREATE VIEW TO GMS_ADMIN;
GRANT CREATE PROCEDURE TO GMS_ADMIN;
GRANT CREATE SEQUENCE TO GMS_ADMIN;
GRANT CREATE TRIGGER TO GMS_ADMIN;
GRANT CREATE TYPE TO GMS_ADMIN;
GRANT CREATE SYNONYM TO GMS_ADMIN;
GRANT CREATE MATERIALIZED VIEW TO GMS_ADMIN;
GRANT CREATE DATABASE LINK TO GMS_ADMIN;
GRANT CREATE JOB TO GMS_ADMIN;

-- Create application connection user (for backend application)
CREATE USER GMS_APP IDENTIFIED BY "App@2024#Connect"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

GRANT CONNECT TO GMS_APP;
GRANT CREATE SESSION TO GMS_APP;

-- Create role-based users for testing
-- Student user
CREATE USER GMS_STUDENT IDENTIFIED BY "Student@2024"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

GRANT CONNECT TO GMS_STUDENT;
GRANT CREATE SESSION TO GMS_STUDENT;

-- Lecturer user
CREATE USER GMS_LECTURER IDENTIFIED BY "Lecturer@2024"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

GRANT CONNECT TO GMS_LECTURER;
GRANT CREATE SESSION TO GMS_LECTURER;

-- Academic Affairs user
CREATE USER GMS_ACADEMIC IDENTIFIED BY "Academic@2024"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

GRANT CONNECT TO GMS_ACADEMIC;
GRANT CREATE SESSION TO GMS_ACADEMIC;

-- Dean user
CREATE USER GMS_DEAN IDENTIFIED BY "Dean@2024"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

GRANT CONNECT TO GMS_DEAN;
GRANT CREATE SESSION TO GMS_DEAN;

-- Department Head user
CREATE USER GMS_DEPT_HEAD IDENTIFIED BY "DeptHead@2024"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

GRANT CONNECT TO GMS_DEPT_HEAD;
GRANT CREATE SESSION TO GMS_DEPT_HEAD;

-- Relative user
CREATE USER GMS_RELATIVE IDENTIFIED BY "Relative@2024"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

GRANT CONNECT TO GMS_RELATIVE;
GRANT CREATE SESSION TO GMS_RELATIVE;

-- Display created users
SELECT username, account_status, default_tablespace
FROM dba_users
WHERE username LIKE 'GMS_%'
ORDER BY username;

COMMIT;